In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
hospital_data = pd.read_csv('/content/hospital.csv')
hospital_data

,Admission_ID,Name,Age,Gender,BMI,Ethnicity,Height,Weight,Blood_Type,Medical_Condition,...,Doctor,Hospital,Insurance_Provider,Billing_Amount,Room_Number,Admission_Type,Discharge_Date,Medication,Test_Results,Days_Hospitalised
0,4ba0c14a-62d9-43ae-9f9f-6ba24017f808,Tara Thomas,25,Male,29.57,African American,180,96,B+,Cancer,...,Susan Bauer,PLC Ford,Blue Cross,9982.94,402,Elective,2019-07-21,Lipitor,Normal,10
1,e00b340c-279f-4898-9fbc-054552ad6095,Laura Rivera,77,Female,28.50,Caucasian,178,90,A-,Hypertension,...,Amanda Clark,Henry PLC,Aetna,15340.77,219,Urgent,2023-06-19,Penicillin,Normal,22
2,f119489e-fdb8-4e53-95ff-b55f6e83fb9a,Donna Eaton,32,Male,60.09,African American,158,150,AB-,Arthritis,...,Jennifer Garza,Barrett PLC,Blue Cross,1296.14,290,Elective,2021-02-06,Aspirin,Abnormal,5
3,ed5088d6-d6a1-45f9-b994-db5a178cc659,Angela Yates,62,Female,26.82,Caucasian,173,80,AB+,Asthma,...,Kimberly Hammond,"French Wells, and Schmidt",Cigna,41845.15,144,Urgent,2024-01-06,Aspirin,Inconclusive,14
4,be20cd2f-42b8-4c83-8871-6adf6a1254d7,Cathy Small,51,Female,21.89,Caucasian,158,54,O-,Asthma,...,Wendy Glenn,"Brown, and Jones Weaver",Blue Cross,26786.53,401,Elective,2024-01-19,Ibuprofen,Normal,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40230,b537552f-f48c-4f74-a2d4-5675ff280d23,Debra Hill,50,Male,31.48,Caucasian,180,102,A-,Asthma,...,Joshua Allison,Dixon-Alexander,Medicare,37447.38,118,Urgent,2021-09-30,Ibuprofen,Normal,1
40231,de487242-164f-4327-be43-d4423e8e350d,Matthew Prince,48,Male,15.57,African American,185,54,AB+,Obesity,...,Hailey Matthews,and Tucker Sons,UnitedHealthcare,31950.22,168,Emergency,2020-03-05,Penicillin,Abnormal,3
40232,f51a515b-e8a1-4aac-a438-22093318455c,Allen Scott,46,Male,29.50,Caucasian,183,99,AB+,Obesity,...,Jose Ramos,"Obrien Robertson, and Mcguire",Cigna,46527.89,312,Urgent,2020-10-07,Paracetamol,Abnormal,4
40233,3926e4f1-3b7f-45a0-a6e2-0278f296013d,Nathan Diaz,27,Male,31.96,Caucasian,183,107,B-,Cancer,...,Diana Greer,"and Young Gonzalez Simmons,",UnitedHealthcare,7185.43,466,Elective,2023-04-30,Paracetamol,Inconclusive,4
40234,a129b050-2edc-444b-9036-fc1886798172,Tony Collins,29,Male,33.16,Caucasian,160,85,B-,Asthma,...,Anthony Sanders,"Hammond, and Harris Hill",Medicare,40604.61,104,Elective,2023-09-24,Lipitor,Abnormal,21

In [ ]:
hospital_data.head()

In [4]:
hospital_data.shape

(40235, 21)

In [5]:
hospital_data.columns

Index(['Admission_ID', 'Name', 'Age', 'Gender', 'BMI', 'Ethnicity', 'Height',
       'Weight', 'Blood_Type', 'Medical_Condition', 'Admission_Date', 'Doctor',
       'Hospital', 'Insurance_Provider', 'Billing_Amount', 'Room_Number',
       'Admission_Type', 'Discharge_Date', 'Medication', 'Test_Results',
       'Days_Hospitalised'],
      dtype='object')

In [6]:
hospital_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40235 entries, 0 to 40234
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Admission_ID        40235 non-null  object
 1   Name                40235 non-null  object
 2   Age                 40235 non-null  int64
 3   Gender              40235 non-null  object
 4   BMI                 40235 non-null  float64
 5   Ethnicity           40235 non-null  object
 6   Height              40235 non-null  int64
 7   Weight              40235 non-null  int64
 8   Blood_Type          40235 non-null  object
 9   Medical_Condition   40235 non-null  object
 10  Admission_Date      40235 non-null  object
 11  Doctor              40235 non-null  object
 12  Hospital            40235 non-null  object
 13  Insurance_Provider  40235 non-null  object
 14  Billing_Amount      40235 non-null  float64
 15  Room_Number         40235 non-null  int64
 16  Admission_Type      40235 non-null  object
 17  Discharge_Date      40235 non-null  object
 18  Medication          40235 non-null  object
 19  Test_Results        40235 non-null  object
 20  Days_Hospitalised   40235 non-null  int64
dtypes: float64(2), int64(5), object(14)
memory usage: 6.4+ MB

In [7]:
hospital_data.describe()

,Age,BMI,Height,Weight,Billing_Amount,Room_Number,Days_Hospitalised
count,40235.000000,40235.000000,40235.000000,40235.000000,40235.000000,40235.000000,40235.000000
mean,51.697353,29.285556,169.915074,84.565279,25559.602930,300.946017,15.524692
std,19.575471,8.292590,10.674313,25.074380,14220.951676,115.337540,8.657143
min,18.000000,14.840000,137.000000,39.000000,-2008.490000,101.000000,1.000000
25%,35.000000,23.720000,163.000000,67.000000,13236.500000,202.000000,8.000000
50%,52.000000,27.760000,170.000000,81.000000,25544.680000,302.000000,16.000000
75%,69.000000,33.060000,178.000000,98.000000,37836.790000,401.000000,23.000000
max,85.000000,67.810000,196.000000,186.000000,52764.280000,500.000000,30.000000

In [8]:
hospital_data.isnull().sum()

Admission_ID          0
Name                  0
Age                   0
Gender                0
BMI                   0
Ethnicity             0
Height                0
Weight                0
Blood_Type            0
Medical_Condition     0
Admission_Date        0
Doctor                0
Hospital              0
Insurance_Provider    0
Billing_Amount        0
Room_Number           0
Admission_Type        0
Discharge_Date        0
Medication            0
Test_Results          0
Days_Hospitalised     0
dtype: int64

In [9]:
hospital_data.duplicated().sum()

np.int64(0)

In [10]:
hospital_data.drop_duplicates(inplace=True)

In [11]:
hospital_data['Admission_Date'].dtype

dtype('O')

In [12]:
hospital_data.isnull().sum()

Admission_ID          0
Name                  0
Age                   0
Gender                0
BMI                   0
Ethnicity             0
Height                0
Weight                0
Blood_Type            0
Medical_Condition     0
Admission_Date        0
Doctor                0
Hospital              0
Insurance_Provider    0
Billing_Amount        0
Room_Number           0
Admission_Type        0
Discharge_Date        0
Medication            0
Test_Results          0
Days_Hospitalised     0
dtype: int64

In [13]:
hospital_data.columns

Index(['Admission_ID', 'Name', 'Age', 'Gender', 'BMI', 'Ethnicity', 'Height',
       'Weight', 'Blood_Type', 'Medical_Condition', 'Admission_Date', 'Doctor',
       'Hospital', 'Insurance_Provider', 'Billing_Amount', 'Room_Number',
       'Admission_Type', 'Discharge_Date', 'Medication', 'Test_Results',
       'Days_Hospitalised'],
      dtype='object')

In [14]:
hospital_data['Admission_Date'] = pd.to_datetime(hospital_data['Admission_Date'])

In [15]:
hospital_data['Discharge_Date'] = pd.to_datetime(hospital_data['Discharge_Date'])

In [16]:
hospital_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40235 entries, 0 to 40234
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Admission_ID        40235 non-null  object
 1   Name                40235 non-null  object
 2   Age                 40235 non-null  int64
 3   Gender              40235 non-null  object
 4   BMI                 40235 non-null  float64
 5   Ethnicity           40235 non-null  object
 6   Height              40235 non-null  int64
 7   Weight              40235 non-null  int64
 8   Blood_Type          40235 non-null  object
 9   Medical_Condition   40235 non-null  object
 10  Admission_Date      40235 non-null  datetime64[ns]
 11  Doctor              40235 non-null  object
 12  Hospital            40235 non-null  object
 13  Insurance_Provider  40235 non-null  object
 14  Billing_Amount      40235 non-null  float64
 15  Room_Number         40235 non-null  int64
 16  Admission_Type      40235 non-null  object
 17  Discharge_Date      40235 non-null  datetime64[ns]
 18  Medication          40235 non-null  object
 19  Test_Results        40235 non-null  object
 20  Days_Hospitalised   40235 non-null  int64
dtypes: datetime64[ns](2), float64(2), int64(5), object(12)
memory usage: 6.4+ MB

In [17]:
hospital_data['Admission_Date'].isnull().sum()

np.int64(0)

In [18]:
hospital_data["BMI_Category"] = pd.cut(hospital_data["BMI"],bins=[0,18.5,25,30,100], labels=["Underweight","Normal","Overweight","Obese"])

In [19]:
hospital_data['Age_Group'] = pd.cut(hospital_data['Age'], bins=[0,18,35,50,65,100], labels=["0-18","19-35","36-50","51-65","65+"])

In [20]:
hospital_data['Billing_Category'] = pd.cut(hospital_data['Billing_Amount'], bins=[0,10000,25000,50000,100000], labels=["Low","Medium","High","Very High"])

In [21]:
hospital_data['Stay_Category'] = pd.cut(hospital_data['Days_Hospitalised'], bins=[0,5,10,20,50], labels=["Short Stay","Medium Stay","Long Stay","Critical Stay"])

In [22]:
hospital_data['Discharge_Year'] = (hospital_data['Discharge_Date'].dt.year)

In [23]:
hospital_data['Discharge_Month'] = (hospital_data['Discharge_Date'].dt.month_name())

In [24]:
hospital_data['Medical_Condition'].value_counts()

Medical_Condition
Arthritis       6821
Diabetes        6796
Cancer          6688
Hypertension    6678
Obesity         6635
Asthma          6617
Name: count, dtype: int64

In [ ]:
hospital_data['Billing_Amount'].describe()

In [ ]:
hospital_data['Medical_Condition'].value_counts()

In [ ]:
hospital_data['Admission_Type'].value_counts()

In [ ]:
hospital_data.groupby('Medical_Condition')['Billing_Amount'].mean().sort_values(ascending=False)

In [ ]:
hospital_data.groupby('Medical_Condition')['Days_Hospitalised'].mean().sort_values(ascending=False)

In [ ]:
hospital_data['Gender'].value_counts()

In [ ]:
hospital_data.groupby('Insurance_Provider')['Billing_Amount'].sum().sort_values(ascending=False)

In [ ]:
hospital_data.groupby('Hospital')['Billing_Amount'].sum().sort_values(ascending=False)

In [36]:
hospital_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40235 entries, 0 to 40234
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Admission_ID        40235 non-null  object
 1   Name                40235 non-null  object
 2   Age                 40235 non-null  int64
 3   Gender              40235 non-null  object
 4   BMI                 40235 non-null  float64
 5   Ethnicity           40235 non-null  object
 6   Height              40235 non-null  int64
 7   Weight              40235 non-null  int64
 8   Blood_Type          40235 non-null  object
 9   Medical_Condition   40235 non-null  object
 10  Admission_Date      40235 non-null  datetime64[ns]
 11  Doctor              40235 non-null  object
 12  Hospital            40235 non-null  object
 13  Insurance_Provider  40235 non-null  object
 14  Billing_Amount      40235 non-null  float64
 15  Room_Number         40235 non-null  int64
 16  Admission_Type      40235 non-null  object
 17  Discharge_Date      40235 non-null  datetime64[ns]
 18  Medication          40235 non-null  object
 19  Test_Results        40235 non-null  object
 20  Days_Hospitalised   40235 non-null  int64
 21  BMI_Category        40235 non-null  category
 22  Age_Group           40235 non-null  category
 23  Billing_Category    40158 non-null  category
 24  Stay_Category       40235 non-null  category
 25  Discharge_Year      40235 non-null  int32
 26  Discharge_Month     40235 non-null  object
dtypes: category(4), datetime64[ns](2), float64(2), int32(1), int64(5), object(13)
memory usage: 7.1+ MB

In [37]:
hospital_data.head()

,Admission_ID,Name,Age,Gender,BMI,Ethnicity,Height,Weight,Blood_Type,Medical_Condition,...,Discharge_Date,Medication,Test_Results,Days_Hospitalised,BMI_Category,Age_Group,Billing_Category,Stay_Category,Discharge_Year,Discharge_Month
0,4ba0c14a-62d9-43ae-9f9f-6ba24017f808,Tara Thomas,25,Male,29.57,African American,180,96,B+,Cancer,...,2019-07-21,Lipitor,Normal,10,Overweight,19-35,Low,Medium Stay,2019,July
1,e00b340c-279f-4898-9fbc-054552ad6095,Laura Rivera,77,Female,28.50,Caucasian,178,90,A-,Hypertension,...,2023-06-19,Penicillin,Normal,22,Overweight,65+,Medium,Critical Stay,2023,June
2,f119489e-fdb8-4e53-95ff-b55f6e83fb9a,Donna Eaton,32,Male,60.09,African American,158,150,AB-,Arthritis,...,2021-02-06,Aspirin,Abnormal,5,Obese,19-35,Low,Short Stay,2021,February
3,ed5088d6-d6a1-45f9-b994-db5a178cc659,Angela Yates,62,Female,26.82,Caucasian,173,80,AB+,Asthma,...,2024-01-06,Aspirin,Inconclusive,14,Overweight,51-65,High,Long Stay,2024,January
4,be20cd2f-42b8-4c83-8871-6adf6a1254d7,Cathy Small,51,Female,21.89,Caucasian,158,54,O-,Asthma,...,2024-01-19,Ibuprofen,Normal,27,Normal,51-65,High,Critical Stay,2024,January

In [39]:
hospital_data.shape

(40235, 27)

In [40]:
hospital_data.to_csv("hospital_cleaned.csv", index=False)

In [41]:
!ls

hospital_cleaned.csv  hospital.csv  sample_data